# -*- coding: utf-8 -*-
"""DlLab7-5may.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZoUXBARtCYhZstQUwXEwcaztwKfVpNyW
"""

!pip install transformers datasets -q

# =========================
# INSTALL (run once)
# =========================
!pip install transformers datasets -q


# =========================
# IMPORTS
# =========================
import torch
from transformers import BertTokenizerFast, BertForQuestionAnswering
from transformers import Trainer, TrainingArguments
from datasets import load_dataset


# =========================
# DEVICE SETUP (IMPORTANT)
# =========================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)


# =========================
# LOAD DATASET
# =========================
dataset = load_dataset("squad")

# Reduce size (Colab friendly)
train_dataset = dataset["train"].select(range(2000))
val_dataset = dataset["validation"].select(range(1000))


# =========================
# TOKENIZER
# =========================
tokenizer = BertTokenizerFast.from_pretrained("bert-base-uncased")


# =========================
# PREPROCESS FUNCTION
# =========================
def preprocess(example):
    inputs = tokenizer(
        example["question"],
        example["context"],
        truncation=True,
        padding="max_length",
        max_length=384,
        return_offsets_mapping=True
    )

    offsets = inputs.pop("offset_mapping")
    start_positions = []
    end_positions = []

    for i, offset in enumerate(offsets):
        answer = example["answers"][i]
        start_char = answer["answer_start"][0]
        end_char = start_char + len(answer["text"][0])

        sequence_ids = inputs.sequence_ids(i)

        # Find context start and end
        idx = 0
        while sequence_ids[idx] != 1:
            idx += 1
        context_start = idx

        while sequence_ids[idx] == 1:
            idx += 1
        context_end = idx - 1

        # If answer not found
        if offset[context_start][0] > end_char or offset[context_end][1] < start_char:
            start_positions.append(0)
            end_positions.append(0)
        else:
            for j in range(context_start, context_end + 1):
                if offset[j][0] <= start_char < offset[j][1]:
                    start_positions.append(j)
                if offset[j][0] < end_char <= offset[j][1]:
                    end_positions.append(j)

    inputs["start_positions"] = start_positions
    inputs["end_positions"] = end_positions

    return inputs


# Apply preprocessing
train_dataset = train_dataset.map(preprocess, batched=True, remove_columns=train_dataset.column_names)
val_dataset = val_dataset.map(preprocess, batched=True, remove_columns=val_dataset.column_names)


# =========================
# FORMAT FOR PYTORCH
# =========================
train_dataset.set_format(type="torch")
val_dataset.set_format(type="torch")


# =========================
# MODEL
# =========================
model = BertForQuestionAnswering.from_pretrained("bert-base-uncased")
model.to(device)   # 🔥 move model to GPU


# =========================
# TRAINING ARGUMENTS
# =========================
training_args = TrainingArguments(
    output_dir="./qa_results",
    eval_strategy="epoch",
    save_strategy="epoch",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=2,
    logging_dir="./logs",
)


# =========================
# TRAINER
# =========================
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
)


# =========================
# TRAIN
# =========================
trainer.train()


# =========================
# TEST (INFERENCE)
# =========================
question = "Where do I live?"
context = "My name is Yash and I live in Delhi."

inputs = tokenizer(question, context, return_tensors="pt")

# 🔥 Move inputs to SAME device
inputs = {k: v.to(device) for k, v in inputs.items()}

with torch.no_grad():
    outputs = model(**inputs)

start = torch.argmax(outputs.start_logits).item()
end = torch.argmax(outputs.end_logits).item()

answer = tokenizer.convert_tokens_to_string(
    tokenizer.convert_ids_to_tokens(inputs["input_ids"][0][start:end+1])
)

print("Answer:", answer)

